### ISSUE TITLE
xCode 9 build issue with pods

### ISSUE THREAD

**Issue by williamoconnorme** [popcorn-official/PopcornTimeTV#2]
Project fails to build in xCode 9 due to some of the dependencies (ObjectMapper and AlamofireXMLRPC)

I've an updated podfile to resolve this until the those projects are updated/merged with their master branch. This will allow the project to be compiled.

https://gist.github.com/williamoconnorme/61e77a1b92babff51e3c0a8c042de76e

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/xcode-9-build-issue-with-pods/132
