### ISSUE TITLE
BUG: App crashes on second consecutively loaded movie

### ISSUE THREAD

**Issue by jackthias** [popcorn-official/PopcornTimeTV#3]
App version: 3.2.12
tvOS version: 11.2.6

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Find seeders and begin playing the second piece of content.

#### Actual Behaviour

After pressing play, the spinning wheel comes up, but never goes to the loading bar/seeding screen. It spends about half a minute on the spinning wheel screen and then the app crashes and bounces back to the Apple TV's spring board.

#### Steps to reproduce the behaviour

1. Find a piece content through search (I used dictation if that's relevant and was only selecting movies).
2. Select the piece of content and begin playing.
3. Watch content and eventually exit using the menu button, or allow video to close and navigation to return to the title selection after playback has finished.
4. Find another piece content through search.
5. Select and play content.
6. Application crashes.

**Comment by jackthias** [comment]
Possibly related: I've also experienced a crash mid-playback, but there was no obvious cause, and as such I can't reproduce it.

**Comment by jackthias** [comment]
I have not tested this for shorter watch sessions, it's possible that this doesn't occur if the first piece of content is only viewed for a few minutes. So far, all occurrences of this bug have been organic for me, at the completion of movies lasting several hours.

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/bug-app-crashes-on-second-consecutively-loaded-movie/133
